### ISSUE TITLE
Can't use Vim Plug and it shows errors when entering neovim

### ISSUE THREAD

**Issue by mrluisfer** [TeoDev1611/NeoVim-Config#5]
### Neovim version: 
**v0.5.0**

### Operating System: 
**Linux - using the distro KDE Neon**
using the version for the end user, which would be the LTS

### Description:
Clone the repository inside my **/.config** folder to have the repository files
The steps to clone them were those of the documentation, but when entering it doesn't allow me to use the vim plug or install any plugin, the init.lua simply doesn't process it

### Screenshot(s):
![Error entering neovim](https://user-images.githubusercontent.com/65029792/126323681-607336af-b3de-466d-ab44-c50b08f6aedd.png)

**Comment by TeoDev1611** [comment]
A little question if you run this in vim:
```
:lua vim.fn.has("linux")
```
Whats show?

**Comment by TeoDev1611** [comment]
Fixed and close for not response

**Comment by mrluisfer** [comment]
> A little question if you run this in vim:
> 
> ```
> :lua vim.fn.has("linux")
> ```
> 
> Whats show?

Does nothing
![nvb](https://user-images.githubusercontent.com/65029792/127569048-5a7ed358-4e1f-46b2-bdbf-373aa06ed8ef.png)

**Comment by mrluisfer** [comment]
I tried again with the new config according to the **github** record but it still shows me the error, and doesnt allow me to use **Plug**

![sdf](https://user-images.githubusercontent.com/65029792/127569410-e2d8ecc4-27b5-4207-9cfc-115bab7727f1.png)

**Comment by TeoDev1611** [comment]
Press enter and after that run :call dein#install()

**Comment by TeoDev1611** [comment]
Fixed? @mrLuisFer

**Comment by mrluisfer** [comment]
I'm doing it, it's cloning something

**Comment by TeoDev1611** [comment]
Yeah this works 😎When finished show Dein Update Done and can you close and open and all is installed

**Comment by mrluisfer** [comment]
Ok it lets me use it with the theme installed but I get this error and it does not allow me to use vim plug
![asdasd](https://user-images.githubusercontent.com/65029792/127570240-3465ac76-8e3e-4d89-adff-c731bcbc045e.png)

**Comment by TeoDev1611** [comment]
Internal use Dein let me fix this tomorrow please

**Comment by mrluisfer** [comment]
I already did the `:Dein update` but it keeps showing me the same error

**Comment by mrluisfer** [comment]
> Internal use Dein let me fix this tomorrow please

Oks 👍🏻

**Comment by TeoDev1611** [comment]
Hey @mrLuisFer good news i change the package manager check the new instalation instructions and let me know if have a bug

**Comment by TeoDev1611** [comment]
If have a bug open a new issue this is closed
